package edu.vcu.wes.myapplication;

/**
 * Unit Test For testing the random number is between 1 and 4 that sets the radio button answers.
 * For the Take Quiz Activity.
 * Created by Wes on 11/22/2015.
 */
import android.support.test.runner.AndroidJUnit4;
import android.test.AndroidTestCase;
import android.util.Log;
import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertThat;
import static org.hamcrest.core.Is.is;

@RunWith(AndroidJUnit4.class)
public class testTakeQuizResults extends AndroidTestCase{
    private int correct = TakeQuiz.correct;
    private int incorrect = TakeQuiz.wrong;
    private int total = correct + incorrect;
    @Test
    public void testCorrect(){
        //Test the number of correct answers.
        assertThat(correct , is(TakeQuiz.correct));
    }

    @Test
    public void testIncorrect(){
        //Test the number of wrong answers
        assertThat(incorrect, is(TakeQuiz.wrong));
    }

    @Test
    public void testRandom(){
        //Test that the random number generated by the method is between 1 and 4 inclusive.
        int random = TakeQuiz.randomNumber();
        int max = 4;
        int min = 1;
        assertFalse("Error value of random value is too high.", random > max);
        assertFalse("Error value of random value is too low.", random < min);
        Log.e("The random number:", " " + random);

    }
    @Test
    public void testTakeQuiz(){
        //Test that the total number of questions is correct.
        assertThat( total, is(TakeQuiz.total));
    }

}
